name: Build cross compilers
'on':
  workflow_dispatch:
    inputs:
      do_release:
        description: Create a release and upload files? (type "yes" to create)
        required: true
        default: 'no'
      release:
        description: Release tag and name
        required: true
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      upload_url: '${{ steps.create_release.outputs.upload_url }}'
    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        id: create_release
        if: '${{ github.event.inputs.do_release == ''yes'' }}'
        with:
          tag: '${{ github.event.inputs.release }}'
          name: '${{ github.event.inputs.release }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  compile:
    needs: prepare
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        target:
          - aarch64-linux-musl
          - aarch64_be-linux-musl
          - arm-linux-musleabi
          - arm-linux-musleabihf
          - armeb-linux-musleabi
          - armeb-linux-musleabihf
          - armel-linux-musleabi
          - armel-linux-musleabihf
          - armv5l-linux-musleabihf
          - armv7l-linux-musleabihf
          - armv7m-linux-musleabi
          - armv7r-linux-musleabihf
          - i486-linux-musl
          - i686-linux-musl
          - m68k-linux-musl
          - microblaze-linux-musl
          - microblazeel-linux-musl
          - mips-linux-musl
          - mips-linux-musln32sf
          - mips-linux-muslsf
          - mips64-linux-musl
          - mips64-linux-musln32
          - mips64-linux-musln32sf
          - mips64el-linux-musl
          - mips64el-linux-musln32
          - mips64el-linux-musln32sf
          - mipsel-linux-musl
          - mipsel-linux-musln32
          - mipsel-linux-musln32sf
          - mipsel-linux-muslsf
          - or1k-linux-musl
          - powerpc-linux-musl
          - powerpc-linux-muslsf
          - powerpc64-linux-musl
          - powerpc64le-linux-musl
          - powerpcle-linux-musl
          - powerpcle-linux-muslsf
          - riscv64-linux-musl
          - s390x-linux-musl
          - sh2-linux-musl
          - sh2-linux-muslfdpic
          - sh2eb-linux-musl
          - sh2eb-linux-muslfdpic
          - sh4-linux-musl
          - sh4eb-linux-musl
          - x86_64-linux-musl
          - x86_64-linux-muslx32
        repo:
          - richfelker/musl-cross-make
          - pmmp/musl-cross-make
    env:
      TARGET: '${{ matrix.target }}'
      REPO: '${{ matrix.repo }}'
    steps:
      - uses: actions/checkout@v3
      - name: 'Clone ${{ matrix.repo }}'
        run: 'git clone https://github.com/${{ matrix.repo }} mcm'
      - name: 'Build ${{ matrix.target }}'
        run: |-
          make -j4
          make install
          ls output
        working-directory: mcm
      - name: 'Package ${{ matrix.target }}'
        id: package
        run: |-
          tar -czvf ../output-${{ matrix.target }}.tar.gz output/
          echo ::set-output name=source_escaped::${REPO%%/*}_${REPO##*/}
        working-directory: mcm
      - id: upload-artifacts-0
        name: Upload artifacts 0
        if: '${{ success() }}'
        continue-on-error: false
        uses: actions/upload-artifact@v3
        with:
          path: 'output-${{ matrix.target }}.tar.gz'
          name: '${{ matrix.target }}-${{ steps.package.outputs.source_escaped }}'
      - id: upload-releases-0
        name: Upload to releases 0
        uses: actions/upload-release-asset@v1
        if: '${{ github.event.inputs.do_release == ''yes'' }}'
        continue-on-error: false
        with:
          asset_path: 'output-${{ matrix.target }}.tar.gz'
          asset_name: >-
            output-${{ matrix.target }}-${{ steps.package.outputs.source_escaped
            }}.tar.gz
          upload_url: '${{ needs.prepare.outputs.upload_url }}'
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - id: upload-artifacts-1
        name: Upload artifacts 1
        if: '${{ steps.upload-artifacts-0.outcome == ''failure'' }}'
        continue-on-error: false
        uses: actions/upload-artifact@v3
        with:
          path: 'output-${{ matrix.target }}.tar.gz'
          name: '${{ matrix.target }}-${{ steps.package.outputs.source_escaped }}'
      - id: upload-releases-1
        name: Upload to releases 1
        uses: actions/upload-release-asset@v1
        if: >-
          ${{ github.event.inputs.do_release == 'yes' &&
          steps.upload-releases-0.outcome == 'failure' }}
        continue-on-error: false
        with:
          asset_path: 'output-${{ matrix.target }}.tar.gz'
          asset_name: >-
            output-${{ matrix.target }}-${{ steps.package.outputs.source_escaped
            }}.tar.gz
          upload_url: '${{ needs.prepare.outputs.upload_url }}'
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - id: upload-artifacts-2
        name: Upload artifacts 2
        if: '${{ steps.upload-artifacts-1.outcome == ''failure'' }}'
        continue-on-error: false
        uses: actions/upload-artifact@v3
        with:
          path: 'output-${{ matrix.target }}.tar.gz'
          name: '${{ matrix.target }}-${{ steps.package.outputs.source_escaped }}'
      - id: upload-releases-2
        name: Upload to releases 2
        uses: actions/upload-release-asset@v1
        if: >-
          ${{ github.event.inputs.do_release == 'yes' &&
          steps.upload-releases-1.outcome == 'failure' }}
        continue-on-error: false
        with:
          asset_path: 'output-${{ matrix.target }}.tar.gz'
          asset_name: >-
            output-${{ matrix.target }}-${{ steps.package.outputs.source_escaped
            }}.tar.gz
          upload_url: '${{ needs.prepare.outputs.upload_url }}'
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - id: upload-artifacts-3
        name: Upload artifacts 3
        if: '${{ steps.upload-artifacts-2.outcome == ''failure'' }}'
        continue-on-error: false
        uses: actions/upload-artifact@v3
        with:
          path: 'output-${{ matrix.target }}.tar.gz'
          name: '${{ matrix.target }}-${{ steps.package.outputs.source_escaped }}'
      - id: upload-releases-3
        name: Upload to releases 3
        uses: actions/upload-release-asset@v1
        if: >-
          ${{ github.event.inputs.do_release == 'yes' &&
          steps.upload-releases-2.outcome == 'failure' }}
        continue-on-error: false
        with:
          asset_path: 'output-${{ matrix.target }}.tar.gz'
          asset_name: >-
            output-${{ matrix.target }}-${{ steps.package.outputs.source_escaped
            }}.tar.gz
          upload_url: '${{ needs.prepare.outputs.upload_url }}'
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - id: upload-artifacts-4
        name: Upload artifacts 4
        if: '${{ steps.upload-artifacts-3.outcome == ''failure'' }}'
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          path: 'output-${{ matrix.target }}.tar.gz'
          name: '${{ matrix.target }}-${{ steps.package.outputs.source_escaped }}'
      - id: upload-releases-4
        name: Upload to releases 4
        uses: actions/upload-release-asset@v1
        if: >-
          ${{ github.event.inputs.do_release == 'yes' &&
          steps.upload-releases-3.outcome == 'failure' }}
        continue-on-error: true
        with:
          asset_path: 'output-${{ matrix.target }}.tar.gz'
          asset_name: >-
            output-${{ matrix.target }}-${{ steps.package.outputs.source_escaped
            }}.tar.gz
          upload_url: '${{ needs.prepare.outputs.upload_url }}'
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

